# This workflow handles the release process for the Tauri application
# It can be triggered either by pushing a tag or manually through the GitHub Actions UI
name: Release
on:
  # Manual trigger with platform selection
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select platform(s) to build'
        required: true
        type: choice
        options:
          - all
          - linux
          - windows
          - macos-intel
          - macos-arm
      version:
        description: 'Release version'
        type: string
        required: true
      release_type:
        description: 'Release type'
        type: choice
        required: true
        options:
          - production
          - beta
          - alpha
      create_release:
        description: 'Create GitHub release'
        type: boolean
        default: true

jobs:
  build-linux:
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.platform == 'linux' || github.event.inputs.platform == 'all')
    # Required for creating GitHub releases
    permissions:
      contents: write
    # Use the latest Ubuntu environment
    runs-on: ubuntu-22.04
    # Run if: tag push OR workflow_dispatch with platform 'linux'
    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install and configure pnpm package manager
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      # Set up Node.js environment with caching
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Install Rust toolchain
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Install Linux-specific dependencies
      - name: Install dependencies (ubuntu only)
        run: |
          if ! sudo apt-get update; then
            echo "Failed to update package lists"
            exit 1
          fi
          if ! sudo apt-get install -y \
            libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            file \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            libgdk-pixbuf2.0-dev \
            libgdk3.0-cil-dev \
            libcairo2-dev \
            libsoup-3.0-dev \
            libsoup-3.0 \
            libjavascriptcoregtk-4.1-dev \
            libwebkit2gtk-4.1-dev \
            patchelf; then
            echo "Failed to install dependencies"
            exit 1
          fi

      # Set PKG_CONFIG_PATH for system libraries
      - name: Set PKG_CONFIG_PATH
        run: |
          if ! echo "PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig" >> $GITHUB_ENV; then
            echo "Failed to set PKG_CONFIG_PATH"
            exit 1
          fi

      # Install project dependencies using pnpm
      - name: Install dependencies
        run: |
          if ! pnpm install; then
            echo "Failed to install project dependencies"
            exit 1
          fi

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          if ! cd backend/python; then
            echo "Failed to change directory to backend/python"
            exit 1
          fi
          if ! pip install -r requirements.txt; then
            echo "Failed to install Python dependencies"
            exit 1
          fi

      # Build Python binary
      - name: Build Python binary
        run: |
          if ! cd backend/python; then
            echo "Failed to change directory to backend/python"
            exit 1
          fi
          if ! pyinstaller --onefile --name fastapi_server main.py; then
            echo "Failed to build Python binary"
            exit 1
          fi
          if ! mkdir -p ../../src-tauri/resources; then
            echo "Failed to create resources directory"
            exit 1
          fi
          if ! cp dist/fastapi_server ../../src-tauri/resources/; then
            echo "Failed to copy binary to target directory"
            exit 1
          fi

      # Build the Tauri application
      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_CODE_SIGNING: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY != '' }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v${{ github.event.inputs.version || '0.0.1' }}
          releaseName: v${{ github.event.inputs.version || '0.0.1' }}
          releaseBody: |
            See the assets to download and install this version.
            
            Changes in this version:
            - Release build
          releaseDraft: false
          prerelease: ${{ github.event.inputs.release_type != 'production' }}
          includeUpdaterJson: true

      # Cache build outputs for both Next.js and Tauri
      - name: Cache Build Output
        uses: actions/cache@v3
        with:
          path: |
            out
            src-tauri/target
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

  build-macos-intel:
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.platform == 'macos-intel' || github.event.inputs.platform == 'all')
    # Required for creating GitHub releases
    permissions:
      contents: write
    # Use the latest macOS environment
    runs-on: macos-latest
    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install and configure pnpm package manager
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      # Set up Node.js environment with caching
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Install Rust toolchain
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      # Install project dependencies using pnpm
      - name: Install dependencies
        run: |
          if ! pnpm install; then
            echo "Failed to install project dependencies"
            exit 1
          fi

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          if ! cd backend/python; then
            echo "Failed to change directory to backend/python"
            exit 1
          fi
          if ! pip install -r requirements.txt; then
            echo "Failed to install Python dependencies"
            exit 1
          fi

      # Build Python binary
      - name: Build Python binary
        run: |
          if ! cd backend/python; then
            echo "Failed to change directory to backend/python"
            exit 1
          fi
          if ! pyinstaller --onefile --name fastapi_server main.py; then
            echo "Failed to build Python binary"
            exit 1
          fi
          if ! mkdir -p ../../src-tauri/resources; then
            echo "Failed to create resources directory"
            exit 1
          fi
          if ! cp dist/fastapi_server ../../src-tauri/resources/; then
            echo "Failed to copy binary to target directory"
            exit 1
          fi

      # Build the Tauri application
      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_CODE_SIGNING: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY != '' }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v${{ github.event.inputs.version || '0.0.1' }}
          releaseName: v${{ github.event.inputs.version || '0.0.1' }}
          releaseBody: |
            See the assets to download and install this version.
            
            Changes in this version:
            - Release build
          releaseDraft: false
          prerelease: ${{ github.event.inputs.release_type != 'production' }}
          args: '--target x86_64-apple-darwin'

      # Cache build outputs for both Next.js and Tauri
      - name: Cache Build Output
        uses: actions/cache@v3
        with:
          path: |
            out
            src-tauri/target
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

  build-macos-arm:
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.platform == 'macos-arm' || github.event.inputs.platform == 'all')
    # Required for creating GitHub releases
    permissions:
      contents: write
    # Use the latest macOS environment
    runs-on: macos-latest
    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install and configure pnpm package manager
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      # Set up Node.js environment with caching
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # Install Rust toolchain
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      # Install project dependencies using pnpm
      - name: Install dependencies
        run: |
          if ! pnpm install; then
            echo "Failed to install project dependencies"
            exit 1
          fi

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      # Install Python dependencies
      - name: Install Python dependencies
        run: |
          if ! cd backend/python; then
            echo "Failed to change directory to backend/python"
            exit 1
          fi
          if ! pip install -r requirements.txt; then
            echo "Failed to install Python dependencies"
            exit 1
          fi

      # Build Python binary
      - name: Build Python binary
        run: |
          if ! cd backend/python; then
            echo "Failed to change directory to backend/python"
            exit 1
          fi
          if ! pyinstaller --onefile --name fastapi_server main.py; then
            echo "Failed to build Python binary"
            exit 1
          fi
          if ! mkdir -p ../../src-tauri/resources; then
            echo "Failed to create resources directory"
            exit 1
          fi
          if ! cp dist/fastapi_server ../../src-tauri/resources/; then
            echo "Failed to copy binary to target directory"
            exit 1
          fi

      # Build the Tauri application
      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_CODE_SIGNING: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY != '' }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          tagName: v${{ github.event.inputs.version || '0.0.1' }}
          releaseName: v${{ github.event.inputs.version || '0.0.1' }}
          releaseBody: |
            See the assets to download and install this version.
            
            Changes in this version:
            - Release build
          releaseDraft: false
          prerelease: ${{ github.event.inputs.release_type != 'production' }}
          args: '--target aarch64-apple-darwin'

      # Cache build outputs for both Next.js and Tauri
      - name: Cache Build Output
        uses: actions/cache@v3
        with:
          path: |
            out
            src-tauri/target
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

  build-windows:
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.platform == 'windows' || github.event.inputs.platform == 'all')
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Add Windows code signing certificate
      - name: Import Windows Certificate
        if: env.WINDOWS_SIGN_CERT != ''
        env:
          WINDOWS_SIGN_CERT: ${{ secrets.WINDOWS_SIGN_CERT }}
          WINDOWS_SIGN_CERT_PASSWORD: ${{ secrets.WINDOWS_SIGN_CERT_PASSWORD }}
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          try {
              # Create temporary directory for certificate
              New-Item -ItemType Directory -Force -Path certificate
              
              # Write the base64 certificate content to a file
              $certPath = "certificate\certificate.pfx"
              [System.Convert]::FromBase64String($env:WINDOWS_SIGN_CERT) | Set-Content $certPath -AsByteStream
              
              # Import the certificate to the certificate store
              $certPassword = ConvertTo-SecureString $env:WINDOWS_SIGN_CERT_PASSWORD -AsPlainText -Force
              Import-PfxCertificate -FilePath $certPath -CertStoreLocation Cert:\CurrentUser\My -Password $certPassword
              
              # Clean up
              Remove-Item -Path certificate -Recurse -Force
          }
          catch {
              Write-Error "Failed to import certificate: $_"
              exit 1
          }

      - name: Install project dependencies
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          try {
              pnpm install
          }
          catch {
              Write-Error "Failed to install project dependencies"
              exit 1
          }

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Python dependencies
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          try {
              cd backend/python
              pip install -r requirements.txt
          }
          catch {
              Write-Error "Failed to install Python dependencies"
              exit 1
          }

      - name: Build Python binary
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          try {
              cd backend/python
              pyinstaller --onefile --name fastapi_server main.py
              New-Item -Path "../../src-tauri/resources" -ItemType Directory -Force
              Copy-Item "dist/fastapi_server.exe" -Destination "../../src-tauri/resources/" -Force
          }
          catch {
              Write-Error "Failed to build Python binary"
              exit 1
          }

      - name: Build Tauri App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_CODE_SIGNING: ${{ secrets.WINDOWS_SIGN_CERT != '' }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
          WINDOWS_SIGN_CERT: ${{ secrets.WINDOWS_SIGN_CERT }}
          WINDOWS_SIGN_CERT_PASSWORD: ${{ secrets.WINDOWS_SIGN_CERT_PASSWORD }}
        with:
          tagName: v${{ github.event.inputs.version || '0.0.1' }}
          releaseName: v${{ github.event.inputs.version || '0.0.1' }}
          releaseBody: |
            See the assets to download and install this version.
            
            Changes in this version:
            - Release build
          releaseDraft: false
          prerelease: ${{ github.event.inputs.release_type != 'production' }}
          includeUpdaterJson: true

      - name: Cache Build Output
        uses: actions/cache@v3
        with:
          path: |
            out
            src-tauri/target
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-